/* eslint-disable */
import * as types from "./graphql";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "mutation InsertAndUpdatePoi($insertObjects: [poi_insert_input!]!, $updates: [poi_updates!]!, $deletePhotoParentIds: [uuid!]!, $insertPhotos: [poi_photo_insert_input!]!) {\n  delete_poi_photo(where: {parent_id: {_in: $deletePhotoParentIds}}) {\n    affected_rows\n  }\n  insert_poi(objects: $insertObjects) {\n    affected_rows\n  }\n  update_poi_many(updates: $updates) {\n    affected_rows\n  }\n  insert_poi_photo(objects: $insertPhotos) {\n    affected_rows\n  }\n}\n\nmutation InsertSinglePoi($object: poi_insert_input!) {\n  insert_poi_one(object: $object) {\n    id\n  }\n}\n\nmutation UpdateSinglePoiLatLng($id: uuid!, $lat: numeric!, $lng: numeric!, $modified_at: timestamp!) {\n  update_poi_by_pk(\n    pk_columns: {id: $id}\n    _set: {lat: $lat, lng: $lng, modified_at: $modified_at}\n  ) {\n    id\n  }\n}\n\nquery CreatedPoi($createdAt: timestamp!, $category: String!) {\n  newPoi: poi(where: {category: {_eq: $category}, created_at: {_eq: $createdAt}}) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n  discontinuePoi: poi(\n    where: {category: {_eq: $category}, modified_at: {_lt: $createdAt}}\n  ) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n}\n\nquery Poi($where: poi_bool_exp!) {\n  poi(where: $where) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}\n\nquery CategoryPoi($category: String!) {\n  poi(where: {category: {_eq: $category}, is_deleted: {_eq: false}}) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}": typeof types.InsertAndUpdatePoiDocument;
  "query SearchNeighbors($lat: numeric, $lng: numeric, $distance: Int, $category: String) {\n  search_neighbors(\n    args: {pdistance: $distance, plat: $lat, plng: $lng}\n    where: {_and: {is_deleted: {_eq: false}, category: {_eq: $category}}}\n  ) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}": typeof types.SearchNeighborsDocument;
};
const documents: Documents = {
  "mutation InsertAndUpdatePoi($insertObjects: [poi_insert_input!]!, $updates: [poi_updates!]!, $deletePhotoParentIds: [uuid!]!, $insertPhotos: [poi_photo_insert_input!]!) {\n  delete_poi_photo(where: {parent_id: {_in: $deletePhotoParentIds}}) {\n    affected_rows\n  }\n  insert_poi(objects: $insertObjects) {\n    affected_rows\n  }\n  update_poi_many(updates: $updates) {\n    affected_rows\n  }\n  insert_poi_photo(objects: $insertPhotos) {\n    affected_rows\n  }\n}\n\nmutation InsertSinglePoi($object: poi_insert_input!) {\n  insert_poi_one(object: $object) {\n    id\n  }\n}\n\nmutation UpdateSinglePoiLatLng($id: uuid!, $lat: numeric!, $lng: numeric!, $modified_at: timestamp!) {\n  update_poi_by_pk(\n    pk_columns: {id: $id}\n    _set: {lat: $lat, lng: $lng, modified_at: $modified_at}\n  ) {\n    id\n  }\n}\n\nquery CreatedPoi($createdAt: timestamp!, $category: String!) {\n  newPoi: poi(where: {category: {_eq: $category}, created_at: {_eq: $createdAt}}) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n  discontinuePoi: poi(\n    where: {category: {_eq: $category}, modified_at: {_lt: $createdAt}}\n  ) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n}\n\nquery Poi($where: poi_bool_exp!) {\n  poi(where: $where) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}\n\nquery CategoryPoi($category: String!) {\n  poi(where: {category: {_eq: $category}, is_deleted: {_eq: false}}) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}":
    types.InsertAndUpdatePoiDocument,
  "query SearchNeighbors($lat: numeric, $lng: numeric, $distance: Int, $category: String) {\n  search_neighbors(\n    args: {pdistance: $distance, plat: $lat, plng: $lng}\n    where: {_and: {is_deleted: {_eq: false}, category: {_eq: $category}}}\n  ) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}":
    types.SearchNeighborsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "mutation InsertAndUpdatePoi($insertObjects: [poi_insert_input!]!, $updates: [poi_updates!]!, $deletePhotoParentIds: [uuid!]!, $insertPhotos: [poi_photo_insert_input!]!) {\n  delete_poi_photo(where: {parent_id: {_in: $deletePhotoParentIds}}) {\n    affected_rows\n  }\n  insert_poi(objects: $insertObjects) {\n    affected_rows\n  }\n  update_poi_many(updates: $updates) {\n    affected_rows\n  }\n  insert_poi_photo(objects: $insertPhotos) {\n    affected_rows\n  }\n}\n\nmutation InsertSinglePoi($object: poi_insert_input!) {\n  insert_poi_one(object: $object) {\n    id\n  }\n}\n\nmutation UpdateSinglePoiLatLng($id: uuid!, $lat: numeric!, $lng: numeric!, $modified_at: timestamp!) {\n  update_poi_by_pk(\n    pk_columns: {id: $id}\n    _set: {lat: $lat, lng: $lng, modified_at: $modified_at}\n  ) {\n    id\n  }\n}\n\nquery CreatedPoi($createdAt: timestamp!, $category: String!) {\n  newPoi: poi(where: {category: {_eq: $category}, created_at: {_eq: $createdAt}}) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n  discontinuePoi: poi(\n    where: {category: {_eq: $category}, modified_at: {_lt: $createdAt}}\n  ) {\n    id\n    name\n    address\n    photos(order_by: {order_no: asc}) {\n      image\n    }\n  }\n}\n\nquery Poi($where: poi_bool_exp!) {\n  poi(where: $where) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}\n\nquery CategoryPoi($category: String!) {\n  poi(where: {category: {_eq: $category}, is_deleted: {_eq: false}}) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}",
): typeof import("./graphql").InsertAndUpdatePoiDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query SearchNeighbors($lat: numeric, $lng: numeric, $distance: Int, $category: String) {\n  search_neighbors(\n    args: {pdistance: $distance, plat: $lat, plng: $lng}\n    where: {_and: {is_deleted: {_eq: false}, category: {_eq: $category}}}\n  ) {\n    id\n    category\n    lat\n    lng\n    name\n    description\n    tel\n    url\n    open_time\n    holiday\n    price\n    toilet\n    address\n    is_deleted\n    is_warning\n    photos(order_by: {order_no: asc}) {\n      image\n      order_no\n    }\n    created_by\n    created_at\n    modified_by\n    modified_at\n  }\n}",
): typeof import("./graphql").SearchNeighborsDocument;

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
